package fruitbasket.com.bodyfit.analysis;

/**
 * 描述运动类型的枚举类
 */
public enum ExerciseType {
    FLAT_BENCH_BRABELL_PASS_1,
    FLAT_BENCH_DUMBBELL_FLYE_2,
    FLAT_BENCH_DUMBBELL_PRESS_3,
    INCLINE_DUMBBELL_FLYE_4,
    REVERSE_GRIP_PULLDOWN_5,
    MACHINE_GURLS_6,
    ALTERNATE_DUMBBELL_CURL_7,
    PEC_DECK_FLYE_8,
    INCLINE_DUMBBEL_PRESS_9,
    CABLE_CROSSOVERS_10
}
