/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeHelper */

#ifndef _Included_NativeHelper
#define _Included_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeHelper
 * Method:    filter
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_filter
        (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     NativeHelper
 * Method:    isbelongSegments
 * Signature: ([DI)Z
 */
JNIEXPORT jboolean JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_isbelongSegments
        (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     NativeHelper
 * Method:    dataSelect
 * Signature: ([[DII)[I
 */
JNIEXPORT jintArray JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_dataSelect
        (JNIEnv *, jclass, jobjectArray, jint, jint);

/*
 * Class:     NativeHelper
 * Method:    activityRecognition
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_activityRecognition
        (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     NativeHelper
 * Method:    abnormalDetection
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_abnormalDetection
        (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     NativeHelper
 * Method:    zoomSegment
 * Signature: ([D[DI)I
 */
JNIEXPORT jint JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_zoomSegment
        (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     NativeHelper
 * Method:    timeBalan
 * Signature: ([D[DI)D
 */
JNIEXPORT jdouble JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_timeBalan
        (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     NativeHelper
 * Method:    amplitudeBalan
 * Signature: ([D[DI)D
 */
JNIEXPORT jdouble JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_amplitudeBalan
        (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     NativeHelper
 * Method:    repetitionScore
 * Signature: ([D[DI)D
 */
JNIEXPORT jdouble JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_repetitionScore
        (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     NativeHelper
 * Method:    setScore
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_fruitbasket_com_bodyfit_helper_NativeHelper_setScore
        (JNIEnv *, jclass, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
